components/layouts/Header.tsx

- close #108
- header.ts useEffect hook 수정
- header.ts useEffect hook 수정
- header.ts useEffect hook 수정

[Fix] header.ts useEffect hook 수정 #108

---

pages/findId/index.tsx
pages/findPwd/index.tsx
pages/login/index.tsx
utils/fomatter.ts

- close #110
- onluNum fomatter 생성 및 적용
- onluNum fomatter 생성 및 적용
-

[Feature] onluNum fomatter 생성 및 적용 #110

---

pages/findId/index.tsx
pages/findId/result/index.tsx
pages/findPwd/index.tsx

- close #112
- 아이디찾기/완료 페이지 분기, errorText 렌더링 조건 생성 
- 아이디찾기/완료 페이지 분기, errorText 렌더링 조건 생성 
- 아이디찾기/완료 페이지 분기, errorText 렌더링 조건 생성

[Refactor] 아이디찾기/완료 페이지 분기, errorText 렌더링 조건 생성 #112

---

pages/findId/index.tsx
pages/findPwd/index.tsx
pages/findPwd/result/index.tsx
utils/fomatter.ts

- close #114
- 버튼 disabled error 작업
- 버튼 disabled error 작업
- 버튼 disabled error 작업

[Fix] 버튼 disabled error 작업 #114

---

components/common/drawer/index.tsx
components/common/loading/spin/index.tsx
components/common/modal/index.tsx
components/layouts/MenuModal.tsx
components/layouts/index.tsx
pages/findId/index.tsx
pages/findPwd/index.tsx
pages/login/index.tsx
pages/register/index.tsx
styles/ts/components/box/index.ts
styles/ts/components/buttons/index.ts
styles/ts/components/input/index.ts

- close #116
- 회원가입 react-hook-form 적용
- 회원가입 react-hook-form 적용
- 회원가입 react-hook-form 적용

[Feature] 회원가입 react-hook-form 적용 #116

---

styles/css/reset.css

- close #118
- reset.css refactoring
- reset.css refactoring
- reset.css refactoring

[Refactor] reset.css refactoring #118

---

pages/register/index.tsx
styles/ts/common.ts
styles/ts/components/badge/index.ts
styles/ts/components/box/index.ts

- close #120
- 회원가입 주소검색 모달 퍼블리싱
- 회원가입 주소검색 모달 퍼블리싱
- 회원가입 주소검색 모달 퍼블리싱

[Feature] 회원가입 주소검색 모달 퍼블리싱 #120

---

pages/index.tsx
pages/register/index.tsx

- close #124
- antd tab css overriding
- antd tab css overriding
- antd tab css overriding

[Feature] antd tab css overriding #124

---

components/layouts/index.tsx
pages/index.tsx

- close #126
- 레이아웃 조건부 설정
- 레이아웃 조건부 설정
- 레이아웃 조건부 설정

[Feature] 레이아웃 조건부 설정 #126

---

components/layouts/index.tsx
pages/findId/index.tsx
pages/findId/result/index.tsx
pages/findPwd/index.tsx
pages/index.tsx
pages/register/index.tsx

- close #128
- customTab naming 수정, getVerification 수정
- customTab naming 수정, getVerification 수정
- customTab naming 수정, getVerification 수정

[Refactor] customTab naming 수정, getVerification 수정 #128

---

components/contents/main/matchingList/index.tsx
components/contents/main/myAroundMatching/index.tsx
pages/_document.tsx
pages/index.tsx
styles/ts/components/buttons/index.ts
types/kakao.d.ts

- close #132
- kakaoMap 연동
- kakaoMap 연동
- kakaoMap 연동

[Feature] kakaoMap 연동 #132

---

components/contents/my/myMatchingList/index.tsx
components/contents/my/myProfile/index.tsx
styles/ts/common.ts

- close #136 
- close #139 
- 마이페이지 퍼블리싱, 기준색 추가
- 
- 마이페이지 퍼블리싱, 기준색 추가

[Feature] 마이페이지 퍼블리싱, 기준색 추가

---

components/common/playerCard/index.tsx
styles/ts/components/buttons/index.ts
styles/ts/components/tab/index.ts

- close #137 
- close #142 
- 공통 컴포넌트 생성 - 참여자 목록 카드
- 공통 스타일 생성 및 수정 - 탭, 버튼 색상 
- 
- 공통 컴포넌트 생성 - 참여자 목록 카드

[Feature] 공통 컴포넌트 생성 - 참여자 목록 카드, 공통 스타일 생성 및 수정 - 탭, 버튼 색상 

---

pages/my/index.tsx

- close #144 
- 마이페이지 퍼블리싱
- 
- 마이페이지 퍼블리싱

feature(element) Publish MyPage

---

components/layouts/Header.tsx
styles/css/reset.css

- close #147
- Drawer modal, header heighta 리팩토링
- Drawer modal, header heighta 리팩토링
- Drawer modal, header heighta 리팩토링

 [Refactor] Drawer modal, header heighta 리팩토링 #147

---

components/common/drawer/halfDrawer/index.tsx
components/contents/main/filteringModal/index.tsx
components/contents/main/matchingList/index.tsx
pages/index.tsx

- close #149
- halfModalComponent 생성
- halfModalComponent 생성
- halfModalComponent 생성

[Feature] halfModalComponent 생성 #149

---

components/common/drawer/halfDrawer/index.tsx
components/contents/main/filteringModal/index.tsx
pages/index.tsx
styles/ts/components/box/index.ts

- close #151
- ImgBox heightInit 적용
- ImgBox heightInit 적용
- ImgBox heightInit 적용

[Refactor] ImgBox heightInit 적용 #151

---

components/contents/main/filteringModal/index.tsx
components/contents/main/matchingList/index.tsx
pages/index.tsx
styles/ts/components/tab/index.ts

- close #153
- Filtering Modal RadioBtn 퍼블리싱
- Filtering Modal RadioBtn 퍼블리싱
- Filtering Modal RadioBtn 퍼블리싱

[Feature] Filtering Modal RadioBtn 퍼블리싱 #153

---

components/contents/main/filteringModal/index.tsx
components/contents/main/matchingList/index.tsx
styles/ts/components/buttons/index.ts

- close #155
- 메인 filtering modal 퍼블리싱
- 메인 filtering modal 퍼블리싱 
- 메인 filtering modal 퍼블리싱

[Feature] 메인 filtering modal 퍼블리싱 #155

---

components/contents/main/filteringModal/index.tsx

- close #157
- Filtering Modal SelectBox 퍼블리싱
- Filtering Modal SelectBox 퍼블리싱
- Filtering Modal SelectBox 퍼블리싱

[Feature] Filtering Modal SelectBox 퍼블리싱 #157

---

pages/findPwd/result/index.tsx

- close #159
- jetBrains login test
- jetBrains login test
- jetBrains login test

[Test] jetBrains login test #159

---

components/common/modal/index.tsx
components/contents/main/filteringModal/index.tsx
constants/region.ts

- close #163
- 지역 선택 Modal 퍼블리싱
- 지역 선택 Modal 퍼블리싱
- 지역 선택 Modal 퍼블리싱

[Feature] 지역 선택 Modal 퍼블리싱 #163

---

components/common/modal/index.tsx
components/contents/main/filteringModal/index.tsx
constants/region.ts
tsconfig.json

- close #165
- 지역선택 모달 수정
- 지역선택 모달 수정
- 지역선택 모달 수정

[Feature] 지역선택 모달 수정 #165

---

components/common/modal/index.tsx
components/contents/main/filteringModal/index.tsx

- close #169
- 지역선택 모달기능 디테일 작업 
- 지역선택 모달기능 디테일 작업 
- 지역선택 모달기능 디테일 작업

[Feature] 지역선택 모달기능 디테일 작업 #169

---

components/contents/main/card/index.tsx
pages/detailMatch/index.tsx
pages/index.tsx

- close #171
- 매칭상세 컴포넌트 생성 
- 매칭상세 컴포넌트 생성 
- 매칭상세 컴포넌트 생성

[Feature] 매칭상세 컴포넌트 생성 #171

---

pages/detailMatch/index.tsx

- close #175
- 매칭 상세 floatBtn 리팩토링
- 매칭 상세 floatBtn 리팩토링
- 매칭 상세 floatBtn 리팩토링

[Feature] 매칭 상세 floatBtn 리팩토링 #175

---

components/contents/main/matchingList/index.tsx
next.config.js
pages/main/detailMatch/index.tsx
pages/main/index.tsx

- close #177
- directory 구조 재세팅
- directory 구조 재세팅
- directory 구조 재세팅

[Refactor] directory 구조 재세팅 #177

---

components/common/drawer/halfDrawer/index.tsx
components/contents/main/filteringModal/index.tsx
components/contents/main/matchingList/index.tsx
components/contents/main/myAroundMatching/index.tsx

- close #185
- kakao map maker, infowindow 세팅
- kakao map maker, infowindow 세팅
- kakao map maker, infowindow 세팅

[Feature] kakao map maker, infowindow 세팅 #185

---

components/common/drawer/halfDrawer/index.tsx
components/contents/main/filteringModal/index.tsx
components/contents/main/matchingList/index.tsx
pages/_app.tsx
styles/ts/components/badge/index.ts

- close #190
- consol warning 수정
- consol warning 수정
- consol warning 수정

[Fix] consol warning 수정 #190

---

components/common/modal/index.tsx
components/contents/main/filteringModal/index.tsx
components/contents/main/matchingList/index.tsx

- close #192
- Filtering Modal 상태유지 구현
- Filtering Modal 상태유지 구현
- Filtering Modal 상태유지 구현

[Feature] Filtering Modal 상태유지 구현 #192

---

components/common/drawer/halfDrawer/index.tsx
components/contents/main/filteringModal/index.tsx
pages/findId/index.tsx
pages/register/index.tsx
styles/ts/components/buttons/index.ts
styles/ts/components/select/index.ts
styles/ts/components/tab/index.ts
styles/ts/components/titles/index.ts

- close #194
- initialFilteringValue 리팩토링
- initialFilteringValue 리팩토링
- initialFilteringValue 리팩토링

[Refactor] initialFilteringValue 리팩토링 #194

---

components/contents/post/radio/index.tsx
pages/postMatching/DPicker.tsx
pages/postMatching/index.tsx
styles/ts/components/textarea/index.ts

- close #196 
- close #197 
- close #198 
- 공통 컴포넌트 생성 - textarea
- 컴포넌트 생성 - ButtonStyleRadio
- postMatching(매칭글등록)페이지 퍼블리싱
- 
-

issue 196~198

---

components/contents/main/myAroundMatching/index.tsx
pages/main/detailMatch/index.tsx

- close #203
- kakaomap detail 작업, 매칭상세 floatBtn css 수정
- kakaomap detail 작업, 매칭상세 floatBtn css 수정
- kakaomap detail 작업, 매칭상세 floatBtn css 수정

[Feature] kakaomap detail 작업, 매칭상세 floatBtn css 수정 #203

---

components/layouts/Header.tsx
pages/main/detailMatch/index.tsx
pages/main/index.tsx

- close #205
- FloatBtn z-index 수정, 매칭상세 css 수정
- FloatBtn z-index 수정, 매칭상세 css 수정
- FloatBtn z-index 수정, 매칭상세 css 수정

[Refactor] FloatBtn z-index 수정, 매칭상세 css 수정 #205

---

components/common/loading/skeleton/index.tsx
pages/main/index.tsx

- close #209
- 스켈레톤UI 적용
- 스켈레톤UI 적용
- 스켈레톤UI 적용

[Feature] 스켈레톤UI 적용 #209

---

components/contents/main/myAroundMatching/index.tsx

- close #213
- Kakao map infoWindow clickEvt 연동
- Kakao map infoWindow clickEvt 연동
- Kakao map infoWindow clickEvt 연동

[Feature] Kakao map infoWindow clickEvt 연동 #213

---

pages/main/detailMatch/index.tsx

- close #215
- 매칭디테일 Static Map 생성
- 매칭디테일 Static Map 생성
- 매칭디테일 Static Map 생성

[Feature] 매칭디테일 Static Map 생성 #215

---

.github/workflows/github-actions.yml

- close #217
- CD 구축 테스트
- CD 구축 테스트
- CD 구축 테스트

[Test] CD 구축 테스트 #217

---

pages/register/index.tsx

- close #219
- CD 구축 테스트 
- CD 구축 테스트 
- CD 구축 테스트

[Test] CD 구축 테스트 #219

---

.github/workflows/github-actions.yml

- close #221
- build 압축 파일 생성 테스트 
- build 압축 파일 생성 테스트 
- build 압축 파일 생성 테스트

[Test] build 압축 파일 생성 테스트 #221

---

.github/workflows/github-actions.yml
next.config.js

- close #223
- build 경로 에러 수정
- build 경로 에러 수정
- build 경로 에러 수정

[Test] build 경로 에러 수정 #223

---

components/layouts/Header.tsx

- close #225
- ssh secretkey 테스트
- ssh secretkey 테스트
- ssh secretkey 테스트

[Test] ssh secretkey 테스트 #225

---

.github/workflows/github-actions.yml

- close #227
- CD 구축 테스트
- CD 구축 테스트
- CD 구축 테스트

[Test] CD 구축 테스트 #227

---

package-lock.json

- close #231
- gh-pages 브랜치 생성 및 배포 테스트
- gh-pages 브랜치 생성 및 배포 테스트
- gh-pages 브랜치 생성 및 배포 테스트

[Test] gh-pages 브랜치 생성 및 배포 테스트 #231

---

package-lock.json

- close #233
- CI error 수정
- CI error 수정
- CI error 수정

[Fix] CI error 수정 #233

---

.github/workflows/github-actions.yml

- close #235
- gh-pages 테스트
- gh-pages 테스트
- gh-pages 테스트

[Test] gh-pages 테스트 #235

---

.github/workflows/github-actions.yml

- close #237
- CD 구축 테스트
- CD 구축 테스트
- CD 구축 테스트

[Test] CD 구축 테스트 #237

---

.github/workflows/github-actions.yml
package-lock.json
package.json

- close #239
- CD 구축 테스트
- CD 구축 테스트
- CD 구축 테스트

[Test] CD 구축 테스트 #239

---

.github/workflows/github-actions.yml

- close #241
- github action CD 구축 테스트
- github action CD 구축 테스트
- github action CD 구축 테스트

[Test] github action CD 구축 테스트 #241

---

.github/workflows/github-actions.yml

- close #243
- CD name, email 추가
- CD name, email 추가
- CD name, email 추가

[Test] CD name, email 추가 #243

---

.github/workflows/github-actions.yml

- close #245
- CD git config 수정 
- CD git config 수정 
- CD git config 수정

[Test] CD git config 수정 #245

---

.github/workflows/github-actions.yml
package.json

- close #247
- GH_TOKEN 적용
- GH_TOKEN 적용
- GH_TOKEN 적용

[Test] GH_TOKEN 적용 #247

---

next.config.js

- close #249
- 배포 404 오류 수정
- 배포 404 오류 수정
- 배포 404 오류 수정

[Chore] 배포 404 오류 수정 #249

---

next.config.js

- close #251
- next config 수정
- next config 수정
- next config 수정

[Test] next config 수정 #251

---

next.config.js
pages/login/index.tsx

- close #255
- basePath 설정
- basePath 설정
- basePath 설정

[Test] basePath 설정 #255

---

next.config.js
pages/login/index.tsx

- close #257
- WebPack 설정 수정
- WebPack 설정 수정
- WebPack 설정 수정

[Test] WebPack 설정 수정 #257

---

next.config.js
pages/login/index.tsx

- close #259
- basePath 수정
- basePath 수정
- basePath 수정

[Test] basePath 수정 #259

---

components/common/playerCard/index.tsx
components/common/playerCard/reportUserModal/index.tsx
components/common/playerCard/userInfoModal/index.tsx
components/contents/my/collapse/index.tsx
components/contents/my/myMatchingList/index.tsx

- close #263 
- clode #264 
- feat(ReportUserModal) Create new component
- feat(UserInfoMadal) Create new component and Apply
- Changes(variable name) Change "userId" to "userEmail"
- Changes(variable name) Change "userId" to "userEmail"
-

[Feature] 유저 정보 모달, 유저 신고 모달 생성

---

next.config.js

- close #266
- base 도메인 롤백
- base 도메인 롤백
- base 도메인 롤백

[Fix] base 도메인 롤백 #266

---

next.config.js

- close #270
- 배포 css,js 에러 테스트
- 배포 css,js 에러 테스트
- 배포 css,js 에러 테스트

[Test] 배포 css,js 에러 테스트 #270

---

package.json
pages/main/index.tsx
tsconfig.json

- close #272
- 절대경로 test 
- 절대경로 test 
- 절대경로 test

[Test] 절대경로 test #272

---

.env
pages/login/index.tsx
pages/main/index.tsx
tsconfig.json

- close #274
- 상대경로 에러 테스트
- 상대경로 에러 테스트
- 상대경로 에러 테스트

[Test] 상대경로 에러 테스트 #274

---

package.json

- close #276
-  export 수정
-  export 수정
-  export 수정

[Test] export 수정 #276

---

.env
next.config.js

- close #278
- env 파일 수정 
- env 파일 수정 
- env 파일 수정

[Test] env 파일 수정 #278

---

next.config.js

- close #280
- 도메인 주소 테스트
- 도메인 주소 테스트
- 도메인 주소 테스트

[Test] 도메인 주소 테스트 #280

---

CNAME

- close #282
- CNAME 설정
- CNAME 설정
- CNAME 설정

[Test] CNAME 설정 #282

---

next.config.js
package.json

- close #284
- css build error 테스트
- css build error 테스트
- css build error 테스트

[Test] css build error 테스트 #284

---

next.config.js

- close #286
- baseURL 변경
- baseURL 변경
- baseURL 변경

[Test] baseURL 변경 #286

---

next.config.js
package.json

- close #288
-  github.io 롤백
-  github.io 롤백
-  github.io 롤백

[Test] github.io 롤백 #288

---

next.config.js

- close #290
- assetPrefix 변경
- assetPrefix 변경
- ㅍ

[Test] assetPrefix 변경 #290

---

constants/prefix.ts
pages/main/index.tsx

- close #292
- prefix create
- prefix create
- prefix create

[Test] prefix create #292

---

.env
constants/prefix.ts

- close #294
- env delete
- env delete
- env delete

[Test] env delete #294

---

pages/main/index.tsx

- close #296
- img 경로 수정
- img 경로 수정
- img 경로 수정

[Test] img 경로 수정 #296

---

constants/prefix.ts
env

- close #298
- env production 생성 
- env production 생성 
- env production 생성

[Feature] env production 생성 #298

---

next.config.js

- close #300
- basePath 변경
- basePath 변경
- basePath 변경

[Test] basePath 변경 #300

---

next.config.js

- close #302
- next config 수정
- next config 수정
- next config 수정

[Test] next config 수정 #302

---

next.config.js

- close #304
- next 경로 수정
- next 경로 수정
- next 경로 수정

[Test] next 경로 수정 #304

---

next.config.js

- close #306
- assetPrefix 상대경로 수정
- assetPrefix 상대경로 수정
- assetPrefix 상대경로 수정

[Test] assetPrefix 상대경로 수정 #306

---

next.config.js
package.json

- close #308
- package.json homepage 삭제
- package.json homepage 삭제
- package.json homepage 삭제

[Test] package.json homepage 삭제 #308

---

next.config.js

- close #310
- redirects delete
- redirects delete
- redirects delete

[Test] redirects delete #310

---

next.config.js
package.json

- close #312
- setting file 롤백
- setting file 롤백
- setting file 롤백

[Feature] setting file 롤백 #312

---

package.json

- close #314
- deploy 수정
- deploy 수정
- deploy 수정

[Test] deploy 수정 #314

---

next.config.js

- close #316
- assetPrefix 수정
- assetPrefix 수정
- assetPrefix 수정

[Test] assetPrefix 수정 #316

---

components/common/datePicker/index.tsx
components/common/drawer/halfDrawer/index.tsx
components/common/drawer/index.tsx
components/common/modal/index.tsx
components/contents/main/card/index.tsx
components/contents/main/matchingList/index.tsx
components/layouts/Header.tsx
constants/prefix.ts
next.config.js
pages/login/index.tsx
pages/main/detailMatch/index.tsx
pages/postMatching/DPicker.tsx
pages/register/index.tsx

- close #318
- 이미지 경로 수정
- 이미지 경로 수정
- 이미지 경로 수정

[Refactor] 이미지 경로 수정 #318

---

next.config.js
package.json

- close #320
- 도메인 배포 테스트
- 도메인 배포 테스트
- 도메인 배포 테스트

[Test] 도메인 배포 테스트 #320

---

constants/prefix.ts

- close #322
- prefix 수정 
- prefix 수정 
- prefix 수정

[Refactor] prefix 수정 #322

---

.github/workflows/github-actions.yml

- close #327
- CICD CNAME 로직 수정
- CICD CNAME 로직 수정
- CICD CNAME 로직 수정

[Fix] CICD CNAME 로직 수정 #327

---

.github/workflows/github-actions.yml

- close #329
- yml 수정
- yml 수정
- yml 수정

[Fix] yml 수정 #329

---

.github/workflows/github-actions.yml

- close #331
-  CNAME 저장소 등록
-  CNAME 저장소 등록
-  CNAME 저장소 등록

[Fix] CNAME 저장소 등록 #331

---

CNAME

- close #333
- 깃헙 권한 테스트
- 깃헙 권한 테스트
- 깃헙 권한 테스트

[Test] 깃헙 권한 테스트 #333

---

.github/workflows/github-actions.yml

- close #335
- 권한 테스트
- 권한 테스트
- 권한 테스트

[Test] 권한 테스트 #335

---

.github/workflows/github-actions.yml

- close #337
- 깃헙 권한 테스트
- 깃헙 권한 테스트
- 깃헙 권한 테스트

[Test] 깃헙 권한 테스트 #337

---

.github/workflows/github-actions.yml

- close #339
- yml 롤백
- yml 롤백
- yml 롤백

[Fix] yml 롤백 #339

---

CNAME
package.json

- close #341
- CNAME 배포테스트
- CNAME 배포테스트
- CNAME 배포테스트

[Test] CNAME 배포테스트 #341

---

pages/_app.tsx

- close #343
- 리다이렉트 코드 추가
- 리다이렉트 코드 추가
- 리다이렉트 코드 추가

[Feature] 리다이렉트 코드 추가 #343

---

next.config.js

- close #345
- next.config 수정
- next.config 수정
- next.config 수정

[Refactor] next.config 수정 #345

---

next.config.js

- close #347
- next config 롤백
- next config 롤백
- next config 롤백

[Fix] next config 롤백 #347

---

lib/http/httpInterceptor.ts
pages/_app.tsx

- close #349
- 백 배포erl 임시적용
- 백 배포erl 임시적용
- 백 배포erl 임시적용

[Feature] 백 배포erl 임시적용 #349

---

pages/_app.tsx

- close #351
- 리다이렉트 기능 수정
- 리다이렉트 기능 수정
- 리다이렉트 기능 수정

[Refactor] 리다이렉트 기능 수정 #351

---

package.json

- close #353
- 개발환경 포트번호 수정
- 개발환경 포트번호 수정
- 개발환경 포트번호 수정

[Feature] 개발환경 포트번호 수정 #353

---

pages/main/index.tsx
service/matching/interface.ts
service/matching/service.ts

- close #367
- Axios 및 Api Service 세팅
- Axios 및 Api Service 세팅
- Axios 및 Api Service 세팅

[Feature] Axios 및 Api Service 세팅 #367

---

components/common/modal/index.tsx
pages/main/detailMatch/index.tsx
pages/main/index.tsx

- close #369
- 모집현황 모달 퍼블리싱
- 모집현황 모달 퍼블리싱
- 모집현황 모달 퍼블리싱

[Feature] 모집현황 모달 퍼블리싱 #369

---

components/common/modal/index.tsx
pages/main/detailMatch/index.tsx
pages/main/index.tsx

- close #378
- CustomModal type error 디버깅
- CustomModal type error 디버깅
- CustomModal type error 디버깅

[Fix] CustomModal type error 디버깅 #378

---

pages/main/detailMatch/index.tsx

- close #380
- 드래그앤드롭 기능 구현
- 드래그앤드롭 기능 구현
- 드래그앤드롭 기능 구현

[Feature] 드래그앤드롭 기능 구현 #380

---

pages/register/index.tsx
service/matches/service.ts

- close #385
- 주소 검색 api 구현
- 주소 검색 api 구현
- 주소 검색 api 구현

[Feature] 주소 검색 api 구현 #385

---

lib/http/httpInterceptor.ts
pages/register/index.tsx
service/matches/service.ts

- close #387
- 주소검색 데이터 연동
- 주소검색 데이터 연동
- 주소검색 데이터 연동

[Feature] 주소검색 데이터 연동 #387

---

pages/register/index.tsx
service/matches/service.ts

- close #394
- 주소검색 api 연동 
- 주소검색 api 연동 
- 주소검색 api 연동

[Feature] 주소검색 api 연동 #394

---

pages/register/index.tsx

- close #396
- 회원가입 셀렉박스 enum 추가
- 회원가입 셀렉박스 enum 추가
- 회원가입 셀렉박스 enum 추가

[Feature] 회원가입 셀렉박스 enum 추가 #396

---

components/layouts/index.tsx
pages/register/index.tsx

- close #398
- 전체적인 레이아웃 padding 값 수정
- 전체적인 레이아웃 padding 값 수정
- 전체적인 레이아웃 padding 값 수정

[Feature] 전체적인 레이아웃 padding 값 수정 #398

---

components/contents/main/card/index.tsx
lib/http/httpInterceptor.ts
pages/main/index.tsx
pages/register/index.tsx
styles/ts/common.ts
styles/ts/components/badge/index.ts
utils/formatter.ts

- close #400
- 매칭조회 무한스크롤 구현
- 매칭조회 무한스크롤 구현
- 매칭조회 무한스크롤 구현

[Feature] 매칭조회 무한스크롤 구현 #400

---

pages/login/index.tsx

- close #402
- 로그인 api 연동
- 로그인 api 연동
- 로그인 api 연동

[Feature] 로그인 api 연동 #402

---

components/contents/main/matchingList/index.tsx
pages/main/index.tsx

- close #404
- 매칭카드 무한스크롤 위치 변경 
- 매칭카드 무한스크롤 위치 변경 
- 매칭카드 무한스크롤 위치 변경

[Refactor] 매칭카드 무한스크롤 위치 변경 #404

---

pages/_document.tsx

- close #408
- kakao mao 오류 디버깅 
- kakao mao 오류 디버깅 
- kakao mao 오류 디버깅

[Fix] kakao mao 오류 디버깅 #408

---

components/contents/main/myAroundMatching/index.tsx

- close #410
- kakao map 내위치 적용 
- kakao map 내위치 적용 
- kakao map 내위치 적용

[Feature] kakao map 내위치 적용 #410

---

components/contents/postMatching/timePicker/TPicker.tsx
pages/post-matching/index.tsx

- close #416
-  빌드 에러 수정
-  빌드 에러 수정
-  빌드 에러 수정

[Fix] 빌드 에러 수정 #416

---

pages/login/index.tsx
pages/register/index.tsx
service/auth/service.ts

- close #418
- yup 임시제거
- yup 임시제거
- yup 임시제거

[Feature] yup 임시제거 #418

---

pages/login/index.tsx
pages/register/index.tsx
service/auth/interface.ts

- close #420
- 스키마 롤백
- 스키마 롤백
- 스키마 롤백

[Feature] 스키마 롤백 #420

---

pages/login/index.tsx

- close #426
- yup error 수정
- yup error 수정
- yup error 수정

[Fix] yup error 수정 #426

---

utils/apiRoot.ts
utils/useCookies.ts

- close #428
- cookie type 설정
- cookie type 설정
- cookie type 설정

[Fix] cookie type 설정 #428

---

components/layouts/MenuDrawer.tsx
pages/login/index.tsx
pages/my/index.tsx
utils/useCookies.ts

- close #430
- menuDrawerBox 로그인 환경 분기
- menuDrawerBox 로그인 환경 분기
- menuDrawerBox 로그인 환경 분기

[Feature] menuDrawerBox 로그인 환경 분기 #430

---

pages/_app.tsx

- close #432
- console.error type 에러 디버깅
- console.error type 에러 디버깅
- console.error type 에러 디버깅

[Fix] console.error type 에러 디버깅 #432

---

service/auth/interface.ts
service/auth/service.ts

- close #434
- 회원가입 이미지 업로드 api 추가
- 회원가입 이미지 업로드 api 추가
- 회원가입 이미지 업로드 api 추가

[Feature] 회원가입 이미지 업로드 api 추가 #434

---

components/common/message/index.tsx
components/layouts/index.tsx
lib/store/common/index.ts
pages/my/index.tsx
utils/useToast.ts

- close #436
- useToast 수정, 마이페이지 에러메시지 적용
- useToast 수정, 마이페이지 에러메시지 적용
- useToast 수정, 마이페이지 에러메시지 적용

[Refactor] useToast 수정, 마이페이지 에러메시지 적용 #436

---

components/contents/main/matchingList/index.tsx
lib/http/httpFileInterceptor.ts
pages/register/index.tsx
service/auth/interface.ts
service/auth/service.ts

- close #438
- fileUpload interceptor 생성, api 연결
- fileUpload interceptor 생성, api 연결
- fileUpload interceptor 생성, api 연결

[Feature] fileUpload interceptor 생성, api 연결 #438

---

components/contents/main/matchingList/index.tsx
lib/http/httpFileInterceptor.ts
pages/register/index.tsx
service/auth/interface.ts
service/auth/service.ts

- close #440 
- close #441
- close #442
- close #443
- close #440 
- close #441
- close #442
- close #443
- 
-

매칭글 등록 페이지 끝!(issue 440~443)

---

components/contents/main/matchingList/index.tsx
lib/http/httpFileInterceptor.ts
pages/register/index.tsx
service/auth/interface.ts
service/auth/service.ts

- close #445 
-  PostMatching 상태값 변경 반영 안되는 이슈 수정
- 
-

[Bug] PostMatching 상태값 변경 반영 안되는 이슈 수정

---

components/contents/main/matchingList/index.tsx
pages/register/index.tsx

- close #447
- 매칭리스트 무한스크롤 에러 수정
- 매칭리스트 무한스크롤 에러 수정
- 매칭리스트 무한스크롤 에러 수정

[Fix] 매칭리스트 무한스크롤 에러 수정 #447

---

pages/register/index.tsx

- close #449
- 회원가입 payload 수정
- 회원가입 payload 수정
- 회원가입 payload 수정

[Feature] 회원가입 payload 수정 #449

---

components/contents/main/myAroundMatching/index.tsx
pages/register/index.tsx

- close #451
- 회원가입 이미지 virtualImgData css 수정
- 회원가입 이미지 virtualImgData css 수정
- 회원가입 이미지 virtualImgData css 수정

[Refactor] 회원가입 이미지 virtualImgData css 수정 #451

---

components/contents/main/myAroundMatching/index.tsx
pages/register/index.tsx

- close #453
-  InputNoTitleButtonBox css 추가
-  InputNoTitleButtonBox css 추가
-  InputNoTitleButtonBox css 추가

[Refactor] InputNoTitleButtonBox css 추가 #453

---

components/contents/main/matchingList/index.tsx

- close #457
- 매칭조회api 수정
- 매칭조회api 수정
- 매칭조회api 수정

[Refactor] 매칭조회api 수정 #457

---

pages/register/index.tsx
service/auth/service.ts
service/matches/interface.ts

- close #459
- Match interface modify
- Match interface modify
- Match interface modify

[Fix] Match interface modify #459

---

pages/login/index.tsx
pages/register/index.tsx
service/auth/interface.ts
service/auth/service.ts

- close #461
- 닉네임 중복체크 api 연동, 로그인 useToast 구현
- 닉네임 중복체크 api 연동, 로그인 useToast 구현
- 닉네임 중복체크 api 연동, 로그인 useToast 구현

[Feature] 닉네임 중복체크 api 연동, 로그인 useToast 구현 #461

---

components/contents/main/matchingList/index.tsx

- close #465
- moveDetailMatching 파라미터 수정
- moveDetailMatching 파라미터 수정
- moveDetailMatching 파라미터 수정

[Fix] moveDetailMatching 파라미터 수정 #465

---

lib/http/httpFileInterceptor.ts
lib/http/httpInterceptor.ts

- close #467
- http interceptor Authorization setting 
- http interceptor Authorization setting 
- http interceptor Authorization setting

[Feature] http interceptor Authorization setting #467

---

components/contents/main/matchingList/index.tsx

- close #469
- 로그인페이지 리다이렉트설정
- 로그인페이지 리다이렉트설정
- 로그인페이지 리다이렉트설정

[Feature] 로그인페이지 리다이렉트설정 #469

---

pages/register/index.tsx
service/auth/interface.ts
service/auth/service.ts

- close #471
- img upload, signup api 연동
- img upload, signup api 연동
- img upload, signup api 연동

[Feature] img upload, signup api 연동 #471

---

pages/register/index.tsx

- close #473
- 회원가입 프로필이미지 에러메시지 구현
- 회원가입 프로필이미지 에러메시지 구현
- 회원가입 프로필이미지 에러메시지 구현

[Feature] 회원가입 프로필이미지 에러메시지 구현 #473

---

components/contents/main/matchingList/index.tsx
pages/register/index.tsx
service/auth/interface.ts
service/auth/service.ts

- close #475 
- close #476 
- close #477
- 뒤로가기 버튼 노출 조건 수정
-메뉴  라우터 Link 태그로 변경
- useRouterHook에 reload 메서드 생성

메뉴 라우터 Link 태그로 변경, 뒤로가기 버튼 노출 조건 수정 (issue#475~477)

---

components/contents/postMatching/searchCourtDrawer/index.tsx
components/contents/postMatching/selector/index.tsx
pages/edit-matching/index.tsx
pages/edit-my-info/index.tsx
pages/post-matching/index.tsx
service/matches/service.ts
service/users/interface.ts
service/users/service.ts

- close #488 
- close #489 
- close #490 
- close #491 
- 
- 
-

issue #488~491

---

.vscode/settings.json
components/common/playerCard/index.tsx
components/common/playerCard/reportUserModal/index.tsx
components/common/playerCard/userInfoModal/index.tsx
components/contents/alarm/AlarmListItem.tsx
components/contents/my/collapse/index.tsx
components/contents/my/myMatchingList/index.tsx
components/contents/my/myProfile/index.tsx
components/contents/postMatching/datePicker/DPicker.tsx
components/contents/postMatching/searchCourtDrawer/index.tsx
constants/userInfoOptions.ts
pages/alarm/index.tsx
pages/edit-matching/index.tsx
pages/edit-my-info/index.tsx
pages/my/index.tsx
pages/post-matching/index.tsx

- close #493 
- colse #494 
- close #495 
- 
- 
-

MyPage, AlarmPage

---

package-lock.json

- close #502
- deploy error 해결
- deploy error 해결
- deploy error 해결

[Fix] deploy error 해결 #502

---

package-lock.json

- close #504
- npm 수정
- npm 수정
- npm 수정

[Fix] npm 수정 #504

---

pages/register/index.tsx
service/auth/interface.ts
service/auth/service.ts

- close #506
- 닉네임 중복체크 api 연결
- 닉네임 중복체크 api 연결
- 닉네임 중복체크 api 연결

[Refactor] 닉네임 중복체크 api 연결 #506

---

service/auth/service.ts

- close #508
- interface delete
- interface delete
- interface delete

[Fix] interface delete #508

---

pages/register/index.tsx
service/auth/interface.ts
service/auth/service.ts

- close #510
- 회원가입 api 수정
- 회원가입 api 수정
- 회원가입 api 수정

[Feature] 회원가입 api 수정 #510

---

pages/register/index.tsx

- close #512
- 회원가입 로직 수정
- 회원가입 로직 수정
- 회원가입 로직 수정

[Refactor] 회원가입 로직 수정 #512

---

pages/login/index.tsx

chore (loginPage) Delete trashes

---

components/contents/my/myMatchingList/index.tsx
components/contents/my/myProfile/index.tsx
pages/_document.tsx
pages/edit-my-info/index.tsx
pages/login/index.tsx
pages/my/index.tsx
service/auth/service.ts

- close #515
- close #516
- close #517
- 
- 
- #517

issue #515 ~ 517

---

components/contents/main/matchingList/index.tsx
components/contents/my/collapse/index.tsx
components/contents/my/myMatchingList/index.tsx
components/contents/my/myProfile/index.tsx
components/contents/postMatching/searchCourtDrawer/index.tsx
components/contents/postMatching/selector/index.tsx
components/layouts/MenuDrawer.tsx
pages/alarm/index.tsx
pages/edit-my-info/index.tsx
pages/login/index.tsx
pages/main/detailMatch/[id].tsx
pages/my/index.tsx
pages/post-matching/index.tsx
service/auth/service.ts
utils/formatter.ts
utils/useCookies.ts
utils/useRouterHook.ts

api 연결 성공, 진행중, 페이지 연결

---

components/contents/my/myMatchingList/index.tsx
components/contents/my/myProfile/index.tsx
pages/edit-my-info/index.tsx
pages/main/detailMatch/[id]/edit-matching/index.tsx
pages/main/detailMatch/[id]/index.tsx
pages/post-matching/index.tsx
service/auth/service.ts
service/matches/interface.ts
service/matches/service.ts
service/users/interface.ts
service/users/service.ts

내정보수정 기능 구현

---

components/contents/my/myMatchingList/index.tsx
components/contents/my/myProfile/index.tsx
pages/edit-my-info/index.tsx
pages/main/detailMatch/[id]/edit-matching/index.tsx
pages/my/index.tsx
service/users/interface.ts
service/users/service.ts

- close #
- 마이페이지 api 콜 위치 변경,  
- 내정보 수정 백엔드 api변경분 반영
- 
-

마이페이지 api 콜 위치 변경,  내정보 수정 백엔드 api변경분 반영

---

pages/edit-my-info/index.tsx

fix (editMyInfo) Add replace

---

components/common/playerCard/reportUserModal/index.tsx
components/contents/my/collapse/index.tsx
components/contents/my/myMatchingList/index.tsx
pages/main/detailMatch/[id]/index.tsx
pages/post-matching/index.tsx
service/users/interface.ts
service/users/service.ts

feat (DetailMatch) Connect Data

---

components/contents/main/DNDModal.tsx/index.tsx

feat(dnd)create component
